# Generated by Django 5.1 on 2024-08-25 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_alter_users_is_superuser_alter_users_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.users'),
        ),
    ]
