# Generated by Django 5.1 on 2024-08-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_alter_resetpasswordtoken_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.users'),
        ),
    ]
