# Generated by Django 5.1 on 2024-08-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_alter_resetpasswordtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='token',
            field=models.CharField(max_length=5),
        ),
    ]
