# Generated by Django 5.1 on 2024-08-25 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_alter_resetpasswordtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
