# Generated by Django 5.1 on 2024-08-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0007_alter_resetpasswordtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='token',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
