# Generated by Django 5.0.7 on 2024-08-19 00:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='uploads/menu_items/')),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('category', models.CharField(choices=[('BadoFood', 'Bado Food'), ('Barbeque', 'Barbeque'), ('Desserts', 'Desserts'), ('DishDay', 'Dish of the Day'), ('EnergyDrinks', 'Energy Drinks'), ('FreakShake', 'Freak Shake'), ('HotDrinks', 'Hot Drinks'), ('IceCoffee', 'Ice Coffee'), ('Juices', 'Juices'), ('Kitchen', 'Kitchen'), ('MilkShake', 'Milk Shake'), ('Pans', 'Pans'), ('Salads', 'Salads'), ('SideDishes', 'Side Dishes'), ('Smoothy', 'Smoothy'), ('Soda', 'Soda'), ('Tagin', 'Tagin')], max_length=50)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_items',
                'ordering': ['name'],
            },
        ),
    ]
