# Generated by Django 5.1 on 2024-08-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_path',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
