# Generated by Django 5.1 on 2024-08-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menuitem_image_path_menuitem_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_data',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/menu_items/'),
        ),
    ]
