# Generated by Django 5.1 on 2024-08-20 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_name_subcategory_menuitem_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_subcategories',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.subcategory'),
        ),
    ]
