# Generated by Django 5.1 on 2024-08-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_category_has_subcategories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='has_subcategories',
            new_name='subcategories',
        ),
    ]
