# Generated by Django 5.1 on 2024-08-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_has_subcategories_category_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='item_id',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
