# Generated by Django 5.1 on 2024-08-21 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menuitem_category_alter_menuitem_image_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='half_price',
        ),
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.ImageField(default='uploads/categories/', upload_to=''),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='quart_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='third_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
