# Generated by Django 5.1 on 2024-08-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_rename_price_menuitem_half_price_category_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_path',
            field=models.ImageField(default='uploads/categories/', upload_to='uploads/menu_items/<django.db.models.fields.CharField>'),
        ),
    ]
